### PR TITLE
Reorder alphabetically. Add Epam

### PR DESCRIPTION
**Pull request by snowinmars**

### CODE REVIEW

**Comment by DAlexIV** [comment]
Thanks for the contribution. I've also had an idea of sorting them alphabetically.
Could you please send a link here to confirm that epam is hiring to some non-Russian office?

**Comment by DAlexIV** [comment]
I've googled myself and merged

**Comment by DAlexIV** [comment]
@snowinmars By the way, what have you meant by assigning N/A to EPAM?

**Comment by snowinmars** [comment]
> @snowinmars By the way, what have you meant by assigning N/A to EPAM?

EPAM stops hiring and relocating during pandemic.

**Pull request merged**
